apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app      # ✅ Proper indentation and normal spaces
  ports:
    - port: 80          # Service port (inside cluster)
      targetPort: 5001  # Your container's port
      nodePort: 30001   # External port on each node
